🔀 :: (#75) 대표뱃지 설정 api
Walkhub/Walkhub-Server pull request #101
Opened 2022-01-13 06:10 UTC by lyutvs

2022-01-13 06:20 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +    @GetMapping("/{user-id}/badges")
Http Method는 PUT 아닌가요?
그리고 엔드포인트가 다른데 확인해주세요

2022-01-13 06:20 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/service/TitleBadgeSettingService.java
> +    public QueryMyPageResponse execute() {
명세서에 맞게 로직도 수정해주세ㅇ여

2022-01-13 06:24 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +    @GetMapping("/{user-id}/badges")
변경 했습니다

2022-01-13 06:24 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +    @GetMapping("/{user-id}/badges")
다른거랑 착각해썽요

2022-01-16 05:13 UTC, jhhong0509 approved these changes

2022-01-16 08:02 UTC, parksangwoo1617 approved these changes

2022-01-17 04:11 UTC, softpeanut requested changes

2022-01-17 04:11 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/service/TitleBadgeSettingService.java
> +    public QueryMyPageResponse execute() {
배지를 사용자가 입력한 배지로 설정해주어야 할 것 같습니다

2022-01-25 02:33 UTC, eogus2513 approved these changes

2022-01-27 07:52 UTC, lyutvs commented
그룹쪽에서 오류 터져서 아마 머지 하면 제대로 작동 할거 같습니다

2022-01-27 13:43 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
>      UNAUTHORIZED_BADGE(401,"BADGE-401-2", "Unauthorized badge");
이거 뭐야...

2022-01-30 15:29 UTC, lyutvs commented
이런 형식으로 짜면 안될거 같은데...일단 해봐요

2022-02-03 14:12 UTC, glay415 approved these changes

2022-02-03 23:32 UTC, glay415 requested changes

2022-02-03 23:32 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +                                                 @RequestBody @Valid UpdateTitleBadgeRequest request) {
명세서에는 이부분이 없던데 왜 만드신건가요?

2022-02-04 09:57 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +                                                 @RequestBody @Valid UpdateTitleBadgeRequest request) {
오잉...? 없어요??
있는걸로 아는데

2022-02-06 15:01 UTC, glay415 approved these changes

2022-02-07 07:14 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
> +    BADGE_NOT_FOUND(404, "BADGE-404-1", "Badge not found"),
에러 메시지 띄어쓰기 후 첫번째 문자 대문자로 해주세요

2022-02-07 07:14 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/service/TitleBadgeSettingService.java
> +
엔터 지워주세요 찡찡

2022-02-07 07:18 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/user/service/TitleBadgeSettingService.java
> +
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUVFRIVEhUYGBgRFRgREhISEREREhIYGBkaGRgYGBgcIS4lHCErHxgYJjgmLS8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHxISHzQhJCE0NDQxNDQ0MTQxNDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0MTQ0NDQxNDE0NDE0MTo0NP/AABEIAMMBAwMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAAABAIDBQEGB//EAEMQAAICAQICBwUECAUCBwEAAAECAAMRBBIFIQYTMUFRYXEiMkKBkRRSobEjM2JygpKywSQ0U2NzFUMWJVSDwtHhB//EABoBAAIDAQEAAAAAAAAAAAAAAAMEAAECBQb/xAApEQADAAIBBAICAgEFAAAAAAAAAQIDESEEEjFBE1EiMgVxoRQjYYGR/9oADAMBAAIRAxEAPwDdxJo87icKRB5u5ark9FpFu7MrKwwZ0N4zGkvBAWXrKRL64KmZon1eZW9eI0ixgVg9sXqtAPk0zLxJBI3ZpiJXsmflZrv2FQlxqglcaCcoGnztAqvkz7K5UUmk9XKKOUX3nUerATcui1lXsXCS9K5xdRV99P51/wDuM12oex1PoymF/L6KrKvs6iyDiXgSDJMb+zKoXKSLpGdk4a5XcaVciDLAJGurnSk2r0E7xXq5Fq411cl1eIRWTvEikgZfZKGhZewsvZBpzMGhDy9G0BkHJ7pZOYhZy9rM1OxU1nvkTRHNsnsjc9U9C1YFvYj9nhHsQl/6pk+FEQZ2RgJx6X0NkoMsMzsG20UcAltZkJJDMuymP0c44ixDTsJo1NF6rYnk4ZICU6hUQF7HVFHMu5CqPUmZ/H+PJpgqqpsut5U0J77nxP3VHLJmRpejdurfrOIvv5hk0qEjTU+RAxvbzMYwdJWXl8ISvOpC3pWrEpoqH1Ldm+sbKB62sMfTMBXxO3m9tOmU/BUhvsH8TEAH5T2Gn4WiKFUAADkqgKo9AInYm0keE6mPpcULxsVvqKo82eiob9dqdVYe8nUPWp/hUgSxeh+i+Knf5u7uT/MZvQh1KXhAXdP2Yo6J6H/0tP8AIJxuiWi7tOi+aFkP1Bm3CWTvr7PPHonUvOq3U1H/AG9VZgfwsSILw7X1fq9WtoHwamkBj5b1PL6T0MJiscV5Rqctz4Z50dJnpIGu0z1DOOvqJv0/qWAyo9RPQ6XUV2qHqZXVhlWVgyn5iDKDyIyD2gjInntXwF6na/h7Cuw+1ZSc/Z78dzL8LH7wieboZfMcMZjqmuKPS7Zzq8xLo/xhNSreyUsr9m6h+T1t5+I8D5zXxOVaqH215HFe1tFHV4lTiN4iuoMuHsJNbELYuwjNglBEcl8DceCvbIGWlZEiEVBEyMIYnZuSwEsEgJMQhlhCSxCVsyLgzoMhidExU6ClgE6okVMtWL2jLOYklE6FkgkUow2SrIEOKcXXTUvawyR7FaD3nduSIPUyaJMMINRrsHnXw9Q37LXuOWf3VGf4prpsLy5EvSEupyKZbNDo5wdg5v1B36m/BsbtFS9orTwA7POexqQKMCZujsCtz7xiXanV9yfWehlJLSOI3vlk9Tqscl7fHwmcTCUXatEZFc4NnJMg7SfDd2Z+csovhCEogQhCQgQVgc4OcHB8j4Qmdb+j1CMPd1ANbju3qCyN8wGHyEhDRhCEhDzfSapqHTX0j26MLeo7baCfaBHeV7RPWae5XRHQ5V1DqfEEZEVurDqyMMhwVYeIIwZk9A7D9l6l+baS19MSe0hDlCfVSJzv5DGnCtDnTW/1Z6SJ3tGnMWevM5kHQgSZcyO2OdVIOkOqDqxQrIlIzs7efZ49pld6leRGIaTc3t6FWkZN5WTDwGRITuZDM4YzMr2Wye+ckIQnxyY0dxOhZzM6pi2QISQS5VnEaMoMxK2Cp6OIJciSaJLkSKUxerKbcIjOexFLH5DMwOhVP+H64821bvqXPed7HaPkuBNLpbb1ei1bDtWl8epGB+cnwfThNPQg7EqRfoonS/jp/F0czq73pDkIQnSEQlWp06OjI6hlbkQf7eEthIQzeF2urWUWHc1WClh7bK2yFY+YwQfTzmlMmlw+qdk5rTV1TsOa72fdtz3kAfLPnNaQjCEISECZnFHD1q9fPZdWQR2giwKw+haaczdGNl99fc4W9B3c8q+PmoPzkIONqlDrX8TKXwBnaoIGSe7mfwMumZwobn1Nv3rOqU/s1Dbj+YvNOQgTH6NLs1XEk+9ZXcB++gH/AMZsTDovFHEHaz2U1dVddVnwdYm7KMe4kEY8Yt1cusTSDYK1R6nEgyS3EDPP7Z0di7rKHEbcRZxCwwssUeUXOT2nMZcRS2NQ9jMLbKGMjmdMiTHsYykElIgwhkQ7mcnITRWjmYBoYhiVm7dFovR43RZEkWN0CcrNwCvwaFZjCxWtoypiVMSo8/8A/wBAP/l+r80A+rqJp6Yewnkij8BFOmNG/Q6tfGliPVfaH5S3hdwemlxzD1o4PqoM6/8AHv8A23/Zzuq8oahCE6AoEz+NWstWKzhrHSpW+7vYKT8gTNCLcS0vW1sgODyZG+66kMp+oEhCek0qVoqVjCqMeZ8ST3k9sulOkd2RTYuxsYZc5wew4I7uWR5SWos2KW2s2PhQAt+JEhCyEwU6QtYM06dyMkB7SlaHHLxJPPyiusr1Fy4su2A89lK+yfJmPtN8sSE2kej0+pRwTWwYKxQkcxkdvPviQO7Vcv8AtUYc+bvlR9EJivDOIlGSi1FTPs1PXyqcj4cdqNy7O/xmulKoXYDBc73bvJAAz8gBIQS4J7K2IeT12vuB7w7l1YeIIImlMduNJsRtjM9ylq60wXZckKxY8lBHefGKaDiltYxqULKCdllZ6x1XPIWDkSQO8SEPRzM6RaVbNNcp5YQurd6sntKwPiCBLtHxWi1ttdis2MlAfbHqvaJn9KdWdg01XO7V/oq1HwqeTufABc/PEqmkm2alPuWje4HqTbp9PY3bZUjt6lRmPSnQ6Vaq66192tFQeijEunmLadPR058HDKHWMESpxKlm0xG4RG0TStESurjWOhzHQk0gTLXSV7Y9FDSezgkgIASUMqLI7ZySzOwncyiudUSMkrwNtll6CN1iJo0arM52ZMBYwsuRzFw0uQxJvkWpFt9QdHQ9jqUPoRiea6FW/wCGWpve0rvpnB7R1bFRn5AT1FYnktSv2TXhuyniXIn4U1Cjln94flOn/H5O1uPsQ6mdrZ6WEITsHPCEJn8L4ibmuKr+jrfqkszk2Mvvkfsg8vkZCFmupfIetwjIMEPzqZfBh3eoMzuKau1tNew2Z2bQ9dhdcE4ck4yuBk9/4TatqVxtdQwPwsAwPhkGBpTaU2jawKldo2kEYIxIy0zMp6OX7BnUImF9hKaeQ5chucnl8p8+1HENcjsju4dWwUFaZ+Qxzn0nTfaKPZrK21j3K7XZLK/JXAO4eAIyPGWvxO88xpUDdzPem0fRSYu1k2N4rxJfkkzzfEuE6ldKj2XKbH2AVNVht5YbQjKeRGAckdxnpdWjGuwL7xRlHqVImZoHsvva2xldawUQqpFSue0V597AyC/njum3DSmlyL5HLr8TxvRbQ3PUvUoo2gV2Waiz9IWX2SuxMkAcwAcchMfiPSDVU22VulWUYqcpYM+Y9rvnseKuumerUopGXWq9UwOtR/ZXcOwsp2kE+cY1mpptIc6F7HHutZVWgHhl2PMfWDp2nwGxfFrdI83odTer6XUvQF+0B6iK3Ul1AJGVbBGCowfPzm30NrWy3XaixT1ovNA3lWNaKiFUGOQ5sSfWMJoDYxfVBGJXYlIG6qlORIXI5k4GT6Y81tBjRakoFAo17jaVG3qrguNpHZhgv1HnBdSqeF/ZUue/8fB6wwhDM8+OnCZW4ljSt5aLRQ6RaxYy+YrZCyHhilqxdhHHWUOscx1wNwxfMMyTCRxGZaCnYTm2dhO5EOZhtkRJgTGSiEkjKSpFjVVRM52XIvYG6QIYyhlYqwSPCWokUbTAUxisxfjHDE1NT1P8XNXHvI45q6nuIODGUEuAmptw9r0K3yeR4TxZ0c6TWezdWMV2HlXqkHY6H73is353i/CKtSmy5MjtVgSr1t3MjDmpE88U1mj5Mraqge66YGrrXwdOQcDnzHPsnb6frYyLVcMRyYWuUa/FLilNzr2ojsPUKcRXo1SE0umUf6SMT94sMkn1JM5ouM6bUBlSxSSCr1v7Fi5HMMjcxEeAarqG+xXnDJn7M55LdX2rgn4lHIj0jqewGno9FCEJZkD5cvPwma/DWf8AXWu6/wCmuKqz+8F5t6E48ppSnV6pK0d7DhUGSf7Ad5MhEWIgUBVAAAwAAAAPADukovoXdkDWKEZssE71XuDftY7YxIQyuPIHFFZAIsvTcCMgqmXbI8ML+MtTg9akFC6AHOxLrRX6bc4inGtUK9Ro2cHYBaWIGQn6tQ7eQyQfWbQMhZ2YXSznXQo999VQKwO3IcE4/hDTY1OpStGexgqINzMxwAB5zJ4NS+rvTVuhSijcNIj5D2ORg3MvcME4HmYHPkmIezeOW6Wj1pkTJGRInmmdJEcyLTs40y3otFNhibvG3EVtSXN86YxBQ7Sl3knEqZY9i7fsZkqLTgMkVkcR6EmFRPMJDM7CfGWcWWKJVJo0UzV2rZTGEEaQxRHly+k5lS6e2BtDCtLqzmUVpG0XE12yhemWrLAZXmSBmWAZMGcnJ3Mzoo8f060FVr6Gt0UtbqBubGH2IrMw3DnjsjXG+HVHS2IUG2qtjXkkshQEqVbOQQe+LK/2jiNjjmmgr6hD3G1+bn5LtHzMd6TWbNJqm8KX/px/eek6WXOJJnOzVuuDN4VTrVppeu5LQ9aOU1KlXBKg4Dp3c+8Ri3jV9QLanSsqLze2q1LEQd7EHDYHb2TT4Ym2mlfu1oPooivSf/Kav9ql1/mBH94wD9mmrAgEdhGQZ5vpA7PdSv8A2tLaj6jlnLNnYD5KdpPqJvK4SsFuQRMt5ALk/lFuCVkVKzD2ribbM95fng+gwPlIUhN+K3I9m9FKVsTsRX6zqx8at7r+JAwfWbVViuqspBVhuUjsIPZiSMyK9BYhb7NcgRiSK7KzYKyeZCEEHHlzkJ5K+kzFRS6pvO56erBUb+tQqBk/tbY1wm0DTVMxyFqUsx7fZX2s/Q/Sdo4cd6vdY1jpkoMBK0OMZVB3+ZJMzbX2aPXJ/pDUKPQhnH4OJRfHgu4Xwx9aa9Tq+VWd+m0nw4+Gy37xPaB3ZE9aBiJcF5afTjwqT+kR0med6jLWS3t+DoRClLQEyJMIRcKRkWnWkGaTt2WiDyhxLHEoczDgNBRasoYy9zKGjGBtPTGYKpEyREgTOjAVBCRhGO5miWJNBIZk1MUy+CmWBY1XFlaWo859t6A0h1CJLrYoLPGZmu6Saeo7XtUt3In6R/5VmIm64lbAUl7PQI8tVp4humLt+o0tjftWlaV+nb+EV1HSDXlS36CoDwV7m59gA5ZPdGZ6W35aQCmj6GGmX0l4t9m09lgGXOEqTvd35Ko8TmYGg4dr7ED6jXOhbn1dNdK4HduJB5zP4Vw179YzPdbbRom9g3PvV9Rjmy45YXJHrHMX8e1SdNaFa6hcpHoejHDDp9OiOdzuTbc/e7vzYn8vlKumjf4LUD74RP53Vf7zcmD0w9qmtP8AU1NCfIWK5/pnWEd7fJuoMBR4ACV6nTK6lHGVbGR44II/KWwkKYjxqstTYg+PbX8mYA/gY6xCjmQAo7yAABOxbX6FLkKWAlSQcBipyOY5iQhmWO2qPLcunHqrag+Pkn58+7toTQ0ubFoZqhWQlppOyuzvKHHLOMZI5jOJXoeHDdZTdZa7JzUNc4FlZ91gAR+6fMecaPR/T5BVCoDbtiO61kntymcHOfCCbZ0ccz2rSKtM6VNXZScVWP1Ngy2zdnajrns9rlnvzGOkVITS61h8dbs3rs2/ksSs4RS99VSLha/09tau4rGCNi7M4GWy38E0Oln+T1X/ABNNehbLpXwb/DlxVUPCtP6RLsyGmPsV/uL+UkWnmsj/ACY7Pg7ugTKmeQ6yUlxsJ2lrGVuZE2SpzK2aUkmbEpczrPK2M3PIWUUtKmltkocw8wMScIlbiWSLRmNoIivM5JYhD96L2RBnd0iwxz8O0+E85rOkLOzV6NA7A7XufIqQ9/7x9JKx75fCM3cx5PRajWJWpax1RQObMcD/APZg3dJnsyNJUWHZ11uUr9VHa0Sq4VuYWalzc47C/uL+6vYJpgYidvHL4W3/AIFby1XjhGe+jut/zV7v/t1nqqx8l5mMabRV1jCKq+g5xiEHWWn/AMf0CSCMcG0ws1HtDK6cBz4F2yEz6AE/SLzb6J14qd++2x2+SnYv4L+MY6OFeTufoW6qu2ePZsX17lZcldyldy+8uRjI8xKeHaFKK0rrGFQepJPMsT3knJJjMJ2DmBMHpAd1/Dk7m1DWH+Ct2H44m9PPdJ26t9HqW9zT2kWtj3VsQoG9AzLIWj0MJxGBAIIIPMEHII7jOyFMIQhIQS4lpEdd1iMxryVNe4WDx2lTmY4FR5dbqz/t7bgR5Z2Z/GelmbZqdSCcadWXJxi9Q5HjgjH4ytGldLhMZ0GjStT1a43YLFsl2PcWJ5k+sS6VD/B6r/if8ozo+JI7FGDJYBk12Da2PFSOTDzBMaurV1ZHGVcFWU9hB5ESa4K3ztjOkf2E/cX+kTrvPLqLNE9KBzZprHFKrZ7T0MwOza/enLGDz5ieiJnBz4HF8+zrYWqnaIu8qNsLYq7STCaG5hMYNkBZFQ86WxBXhYTsGSZAtK1eSzBynLK7dEXMocy5xKWjsaYWSOYZkTOZh1JvRPEJXuhL7WQ8jdbdrOb7qqM+zWDh7QO9z3DymhRSqqFRQqryCqMARD7He/6y/Zn4KUC4/ibJnDwZT223H/3mH5QWa/kf5V/4c1uny+TUhMv/AKSw9zUWr6vvH0aBOpr+7co8B1T/ANwT9IH4pf61snc/aNSES0XEksJUZV196txtdfl3jzEdgqhy9UWnsJ6Douf8NWPus6H1DtPPzU6LX4N9R7VfrVHir9uP4gfqI70NJU19ivVzudnooQhOsc0JG2tXUq4DKw2sCAQQe0ESUJCHm/8Ap+o0nPR/pae06R2w9f8AxOe79k/LE0eG8bquJQEpYvv02ApYvyPb6jImnEOJcHp1AHWoCV92wey6HxVxzWQvex+E899h1un/AFFo1FY7KdSdtgHgtwzn5iSTpQinbq67NM3ebULV/KxcrITRvwi2m19VgBrsRweYKOr5+hk79UiDdY6IBzy7qo/EyFaYlx5Bsrf4q7qyh7xudUYehBImnmeT4tx4X7E0db6nq7EssdPYqAQ7gBYw2nmB2RP/AMRa25Qa0qoVuYZma9wD5YAzMVcyt09BJx1Xg1enN+zTDHNzdUa0BwXZXDYHyU85o8K4omoQPXkcyrIfeRh2qRPHpoiX6y53tcdj2Hkn7iDkvylNovqvV9M+xbeVq7Q9ZYD2WZfMDGfSc/LljNWl6Ojgh41z7PfWNFXMxdH0j9oV6perZuSWBt1Nh7gGPunyM1nMxONrk6OJqjhaG898iTImE7RhIt3S1bIrmSBgqxbKcoa6wSp5UTOq8FMuXort0BEiRJyJEZhllcIZhC7IZEIQnJOcEIQkIJ6/h62gH3XXmli8mU/3HlI8N1hcMrjFlfJ17j4OvkY9Mzi1RXbeg9ur3gPjQ+8v9/lDxXcuyv8Aoj45NORW5qnS5eezIdR2uh94fLAI9IVWB1DKchgGB8jzElBzTx3teirlVOj151adWbc5QIbNw55UDPL5RTT8SbcguqNYsx1bbw6knmEYj3Wx3fLMwOGasVbqbT+gvyqsTjqmfIKk9ynPLwM1NdTsQ0ix7Hs2ipHZCybee/2QMAduT4Cd3FlWSdo5OTG4embsJ [...]

2022-02-07 07:21 UTC, softpeanut approved these changes

2022-02-07 07:22 UTC, merged