🔀 :: (#106) 공지사항 조회 api
Walkhub/Walkhub-Server pull request #111
Opened 2022-01-14 14:53 UTC by glay415

close #106

2022-01-16 08:08 UTC, parksangwoo1617 approved these changes

2022-01-16 15:32 UTC, jeongjiwoo0522 commented
커밋 메세지를 조금만 더 구체적으로 써야할 것 같아요

2022-01-17 00:27 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
> +		return false;
이 부분은 쿼리 안에서 처리해야 되는 부분입니다

2022-01-17 06:59 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
> +	public QueryNoticeListResponse execute() {
@Transactional(readOnly=true) 붙여주시면 감사하겠습니다

2022-01-18 06:21 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
> +		return false;
고쳤읍니다

2022-01-18 06:21 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
> +	public QueryNoticeListResponse execute() {
추가했읍니다

2022-01-18 06:56 UTC, jeongjiwoo0522 requested changes

2022-01-19 14:14 UTC, jeongjiwoo0522 approved these changes

2022-01-19 15:03 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
> +	public List<NoticeResponse> noticeList;
final 한 번만 붙여주세요

2022-01-20 00:33 UTC, jhhong0509 approved these changes

2022-01-20 05:49 UTC, eogus2513 approved these changes

2022-01-20 06:01 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
> +			if(user.getAuthority().equals(Authority.USER) && scope.equals(Scope.TEA)) {
고쳐드렸습니다

2022-01-20 06:01 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
> +	public List<NoticeResponse> noticeList;
붙였습니다

2022-01-20 06:14 UTC, softpeanut approved these changes

2022-01-20 06:21 UTC, merged