🔀 :: (#116) 챌린지 참여자 목록보기
Walkhub/Walkhub-Server pull request #118
Opened 2022-01-17 14:50 UTC by softpeanut

close #116

2022-01-18 03:29 UTC, jeongjiwoo0522 requested changes

2022-01-18 04:02 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsListService.java
> +                .filter(authority -> !user.getAuthority().equals(Authority.USER))
전 커밋에 변경했는데 반영이 안되었나 봅니다ㅠ

2022-01-18 04:28 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsListService.java
> +                .filter(authority -> !user.getAuthority().equals(Authority.USER))
반영 됐네요

2022-01-18 04:28 UTC, jeongjiwoo0522 approved these changes

2022-01-18 04:30 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
> +    List<ChallengeStatus> findByChallengeId(Long challengeId);
궁금한건데 findByChallengeId가 잘 작동 되는 방법인가요 ?

2022-01-19 11:05 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
> +    List<ChallengeStatus> findByChallengeId(Long challengeId);
네 ! 작동됩니다

2022-01-19 11:09 UTC, eogus2513 approved these changes

2022-01-19 12:03 UTC, jeongjiwoo0522 approved these changes

2022-01-20 00:32 UTC, jhhong0509 approved these changes

2022-01-20 00:35 UTC, merged