🔀 :: (#152) teacher verify code
Walkhub/Walkhub-Server pull request #154
Opened 2022-01-24 13:18 UTC by eogus2513

close #152

2022-01-24 13:23 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/teacher/service/VerificationCodeService.java
> +    TeacherAuthCodeRepository teacherAuthCodeRepository;
의존성 주입 해주세요

2022-01-24 23:49 UTC, softpeanut approved these changes

2022-01-24 23:51 UTC, jhhong0509 approved these changes

2022-01-25 03:10 UTC, softpeanut requested changes

2022-01-25 03:10 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
> +    @GetMapping("/verification")
post로 바꿔주세요 !!

2022-01-25 03:17 UTC, jhhong0509 approved these changes

2022-01-25 03:17 UTC, softpeanut approved these changes

2022-01-25 03:19 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
> +    @GetMapping("/verification")
아 endpoint도 바꿔주세요

2022-01-25 06:49 UTC, lyutvs approved these changes

2022-01-25 23:46 UTC, glay415 approved these changes

2022-01-25 23:47 UTC, merged