🔀 ::  (#166) 챌린지 수정 API
Walkhub/Walkhub-Server pull request #179
Opened 2022-01-26 02:55 UTC by lyutvs

2022-01-26 03:04 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
> +    @PatchMapping("/{challenge-id}")
이거....PathVariable로 해야 할까요

2022-01-26 03:14 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
> +    @PatchMapping("/{challenge-id}")
노션에서는 PathVariable로 되어있네요.. 그렇게 해야 될거 같아요

2022-01-26 03:15 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
> +    @PatchMapping("/{challenge-id}")
수정 하는데... PathVariable를 쓰는 이유가 있을까요?

2022-01-26 06:35 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
> +    @PatchMapping("/{challenge-id}")
리소스가 특정하게 정해져 있는 것들은 주로 path param으로 받는다고 하네요

2022-01-26 11:34 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/challenge/service/UpdateChallengeService.java
> +                .UpdateEndAt(request.getEndAt())
얘 왜 대문자로 시작해

2022-01-26 11:34 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +    public Challenge updateScope(Scope scope) {
이거 각각 메소드로 하는것보단 request 객체를 받아서 update하는게 낫지 않아?

2022-01-27 07:52 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +    public Challenge updateScope(Scope scope) {
넵! 수정하겠습니다

2022-01-27 07:53 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/service/UpdateChallengeService.java
> +                .UpdateEndAt(request.getEndAt())
어....조크조크

2022-01-27 07:58 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
> +    @PatchMapping("/{challenge-id}")
생각해서 변경 해보겠습니다 많이 지적해주세여

2022-01-28 12:34 UTC, parksangwoo1617 requested changes

2022-01-28 12:34 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/challenge/service/UpdateChallengeService.java
> +                .updateAward(request.getAward())
여기 goal 두개네요

2022-01-28 14:27 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/service/UpdateChallengeService.java
> +                .updateAward(request.getAward())
엇 수정하겠습니다

2022-01-30 14:07 UTC, eogus2513 commented
Code Smell 해결해 주세요..

2022-02-03 14:47 UTC, eogus2513 commented
Code Smell 해결 해주세요

2022-02-03 14:48 UTC, lyutvs commented
무슨 code smell 인지 모르겠어요

2022-02-03 15:06 UTC, lyutvs commented
저게 뭘까...

2022-02-06 13:09 UTC, jhhong0509 approved these changes

2022-02-06 13:31 UTC, closed without merging