🔀 :: (#236) erd에 따라 Entity 수정
Walkhub/Walkhub-Server pull request #237
Opened 2022-02-07 15:07 UTC by eogus2513

close #236

2022-02-07 15:20 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +        this.createdAt = LocalDate.now();
BaseTimeEntity 상속받으면 되지 않음?

2022-02-07 15:25 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +                     LocalDate createAt, LocalDate endAt, Scope scope, User user) {
createdAt으로 변경해주세요

2022-02-07 15:25 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
> +    @Column()
nest적인 발상 멈춰주세요

2022-02-07 15:25 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/exercise/domain/Location.java
> +    @Digits(integer = 2, fraction = 10)
전에 했던 것이 맞는 것 같아요

2022-02-07 15:25 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
> +        this.createdAt = LocalDate.now();
이거는 BaseTimeEntity를 상속받아서 자동으로 넣어줍니다

2022-02-07 15:25 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +    private LocalDate createdAt;
Basetimeentity 상속받으면 될 것 같아요

2022-02-07 15:28 UTC, softpeanut requested changes

2022-02-07 15:28 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
setAuthCode 메소드 지우면 안 될 것 같아요

2022-02-07 15:44 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +    private LocalDate createdAt;
이거 BaseTimeEntity로 안바꾸나요?

2022-02-07 16:06 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +    private LocalDate createdAt;
챌린지는 생성일 보다는 시작일 개념인거 같아서 추가 안했습니다.

2022-02-07 23:49 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
> +    private LocalDate endAt;
이건 LocalDateTime이 맞을 것 같은데..

2022-02-07 23:49 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
> +    private Long userCount;
Default 값 넣어주세요

2022-02-08 02:16 UTC, glay415 approved these changes
lgtm

2022-02-08 02:17 UTC, softpeanut approved these changes

2022-02-08 02:18 UTC, jhhong0509 approved these changes

2022-02-08 02:19 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +    private LocalDate endAt;
시간 뺀 이유는 뭔가여ㅓㅓ

2022-02-08 02:22 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> +    private LocalDate endAt;
반영이 안된거 같아요

2022-02-08 02:24 UTC, lyutvs approved these changes

2022-02-08 02:25 UTC, merged