🔀 :: (#289) show calorie level
Walkhub/Walkhub-Server pull request #299
Opened 2022-02-10 07:32 UTC by eogus2513

close #289

2022-02-10 11:36 UTC, jhhong0509 approved these changes

2022-02-10 13:52 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/CalorieLevelListResponse.java
> +    public static class CalorieLevelResponse {
명세서대로 수정해주세요

2022-02-10 13:52 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/service/CalorieLevelListService.java
> +    public CalorieLevelListResponse execute() {
@Transactional(readOnly=true) 부탁드립니다

2022-02-10 13:52 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/service/CalorieLevelListService.java
> +                calorieLevelRepository.findAllBy()
여기서 findAll을 안쓰는 이유가 있을까요?

2022-02-10 14:30 UTC, jhhong0509 approved these changes

2022-02-10 14:33 UTC, jhhong0509 requested changes

2022-02-10 23:44 UTC, softpeanut approved these changes

2022-02-11 01:07 UTC, glay415 approved these changes

2022-02-11 01:12 UTC, lyutvs approved these changes

2022-02-11 04:05 UTC, jhhong0509 approved these changes

2022-02-11 04:05 UTC, merged