🔀 :: (#272) 유저 전체 리스트
Walkhub/Walkhub-Server pull request #300
Opened 2022-02-10 07:32 UTC by parksangwoo1617

close #272

2022-02-11 03:22 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserListResponse.java
> +    @NoArgsConstructor
넵

2022-02-11 03:22 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserListResponse.java
> +    private List<UserListInfo> userList;
넵

2022-02-11 17:10 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
> +        }
BooleanBuilder로 변경

2022-02-13 08:15 UTC, softpeanut approved these changes

2022-02-13 11:27 UTC, jhhong0509 requested changes

2022-02-13 11:27 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/global/querydsl/QuerydslUtil.java
> +    public BooleanBuilder nullSafeBuilder(Supplier<BooleanExpression> f) {
이건 static 메소드로 해도 충분하지 않나요?

2022-02-13 11:27 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/global/querydsl/QuerydslUtil.java
> +    public BooleanBuilder nullSafeBuilder(Supplier<BooleanExpression> f) {
아 그리고 이게 필요한 이유가 뭔가요?

2022-02-13 11:27 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
> +        switch (scope) {
이런것들들들은 enum으로 관리하는게 좋지 않을까요?

2022-02-13 11:27 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
> +                .leftJoin(exerciseAnalysis)
이런건 그냥 `leftJoin(user.exerciseAnalysis, exerciseAnalysis)`로 간단하게 표현할 수 있습니다

2022-02-13 13:25 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/global/querydsl/QuerydslUtil.java
> +    public BooleanBuilder nullSafeBuilder(Supplier<BooleanExpression> f) {
조건 반환하는 메소드를 BooleanExpression으로 구현한다고 가정했을 때, gradeAndClassNumEq 메소드에서 만약 grade가 null이면 체이닝이 안된다고 합니다. 그래서 BooleanBuilder를 사용해야했는데 김영한님 코드에서 저 간지나는 메소드를 발견해서 공통 로직도 줄일겸 만들었어용

2022-02-13 13:27 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
> +        switch (scope) {
예아

2022-02-14 23:35 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
> +    public QueryUserListResponse queryUserList(@RequestParam Integer page,
파라미터가 너무 많은 것 같은데...
파라미터 클래스로 관리하는건 어떤가요?

2022-02-15 07:32 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
> +    public QueryUserListResponse queryUserList(@RequestParam Integer page,
@ModelAttribute 말씀하시는거죠?

2022-02-16 16:32 UTC, eogus2513 approved these changes

2022-02-16 19:16 UTC, jhhong0509 approved these changes

2022-02-16 23:51 UTC, lyutvs approved these changes

2022-02-17 03:31 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
> +                .groupBy(user.id)
아마 합계랑 평균 연산하는 것 때문에 그럴 거 같은데 group by 안하면 exerciseAnalysis 테이블에 있는 데이터들을 한 유저에 다 매핑하더라고요 그래서 각각 가져오라고 group by 넣어줬습니다

2022-02-17 06:36 UTC, merged