🔀 :: (#309) 선생님 인증코드 확인 api
Walkhub/Walkhub-Server pull request #310
Opened 2022-02-11 00:04 UTC by glay415

2022-02-11 00:13 UTC, eogus2513 approved these changes

2022-02-11 04:06 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
> +    public void setAuthority(Authority authority) {
이거 `setAuthorityTeacher()`로 바꿔주세요

2022-02-11 04:11 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
> +    public void setAuthority(Authority authority) {
넵

2022-02-12 06:20 UTC, softpeanut commented
code smell 해결해주세요

2022-02-13 07:32 UTC, softpeanut requested changes

2022-02-13 07:32 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/teachers/verification-codes").hasAuthority("USER")
지금 바꾼 permission은 선생님 인증코드를 발급하는 api인데 permission 설정이 필요한 건 선생님 인증코드 확인하는 api인 것 같아요

2022-02-13 11:37 UTC, jhhong0509 approved these changes

2022-02-13 12:39 UTC, softpeanut approved these changes

2022-02-13 14:18 UTC, merged