🔀::  (#307) 유저 뱃지 리스트 조회 API
Walkhub/Walkhub-Server pull request #314
Opened 2022-02-11 04:03 UTC by lyutvs

close #307

2022-02-11 04:08 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
> +    @Column(length = 20)
이거 둘이 같이 쓰면 `@NotNull`이 동작을 안해서 `@NotNull`이랑 `@Size(max = 20)`으로 해주세요

2022-02-11 04:11 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
> +    public QueryUserBadgeListResponse queryUserBadgeList(@PathVariable(name = "badge-id")Long id) {
PathVariable에 `@GetMapping("/{badge-id}")`을 추가해 주세요

2022-02-11 04:13 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
> +    public QueryUserBadgeListResponse queryUserBadgeList(@PathVariable(name = "badge-id")Long id) {
넹

2022-02-11 04:13 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
> +    @Column(length = 20)
넵!

2022-02-11 05:46 UTC, lyutvs commented
로직 처음부터 다시 짤게요

2022-02-11 15:11 UTC, softpeanut requested changes

2022-02-11 15:11 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
> +    public QueryUserBadgeListResponse execute(Long badgeId) {
근데 이거 명세서랑 안맞는 것 같은데..

2022-02-13 07:41 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/QueryUserBadgeListResponse.java
> +        private final boolean isMine;
isMine은 왜 추가하셨나요..

2022-02-13 14:23 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/QueryUserBadgeListResponse.java
> +        private final boolean isMine;
엇 실수

2022-02-14 00:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
> +        List<DefaultBadgeResponse> badgeList = badgeCollectionRepository.findByUserId(userId)
이것만 findAllByUserId로 바꾸면 괜찮을 것 같습니다!

2022-02-14 00:38 UTC, jhhong0509 approved these changes

2022-02-14 04:50 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
> +        List<DefaultBadgeResponse> badgeList = badgeCollectionRepository.findByUserId(userId)
넵!

2022-02-14 15:27 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
> +    public QueryUserBadgeListResponse execute(Long userId) {
넵 추가하겠습니다

2022-02-15 05:12 UTC, softpeanut approved these changes

2022-02-15 05:25 UTC, eogus2513 approved these changes

2022-02-15 05:27 UTC, glay415 approved these changes

2022-02-15 05:29 UTC, merged

2022-02-15 05:29 UTC, jeongjiwoo0522 approved these changes