🔀 :: (#328) 모든 api 검증 / 수정
Walkhub/Walkhub-Server pull request #334
Opened 2022-02-13 19:36 UTC by glay415

2022-02-13 21:37 UTC, jhhong0509 requested changes

2022-02-13 21:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
> -    @Length(max = 8)
이거 @Column의 size로라도 넣어주세요

2022-02-13 21:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/exercise/exception/AlreadyExercisingException.java
> +
여기 엔터가 두 개인 것 같은데..

2022-02-13 21:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveExerciseAnalysisRequest.java
> +    @PositiveOrZero(message = "calorie는 음수를 허용하지 않습니다.")
이거 calorie가 아니라 exerciseTime입니다

2022-02-13 21:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
> -    @Length(max = 7)
여기도 `@Column(size)`

2022-02-14 00:33 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/global/error/ExceptionFilter.java
> +            e.printStackTrace();
이거 클래스에 @Slf4j 붙이고 `logger.error()`으로 필요한 정보들들들 찍으면 security hotspot 해결될 수 있을 것 같은데

2022-02-14 00:58 UTC, eogus2513 approved these changes

2022-02-15 00:37 UTC, jhhong0509 approved these changes

2022-02-15 01:07 UTC, jeongjiwoo0522 approved these changes

2022-02-15 06:40 UTC, lyutvs approved these changes

2022-02-15 09:44 UTC, merged