🔀 :: (#132) 학교 랭킹 조회
Walkhub/Walkhub-Server pull request #336
Opened 2022-02-13 20:37 UTC by glay415

close #132

2022-02-13 21:31 UTC, jhhong0509 requested changes

2022-02-13 21:31 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
> +    public SchoolRankResponse querySchoolRank(@RequestParam com.walkhub.walkhub.domain.rank.domain.type.DateType dateType) {
이거 import가 굉장히 불편하네요..
enum 클래스 이름을 바꾸면 좋을 것 같습니다.

2022-02-14 00:36 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
> +    public SchoolRankResponse querySchoolRank(@RequestParam SchoolDateType schoolDateType) {
이거 API명세대로 파라미터 이름 수정해 주세요

2022-02-14 01:29 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
> +    public SchoolRankResponse querySchoolRank(@RequestParam SchoolDateType schoolDateType) {
enum 클래스 schoolDateType으로 통일했습니다

2022-02-14 05:08 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
> +	public SchoolRankResponse execute(SchoolDateType schoolDateType) {
@Transactional(readOnly=true) 붙여주시면 더 좋을 것 같아요

2022-02-14 05:08 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
> +			.findAllByDateTypeAndCreatedAtBetweenOrderByRankingDesc(dateType.toString(), localDate, LocalDate.now())
Asc 아닌가요?

2022-02-14 05:09 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
> +    public SchoolRankResponse querySchoolRank(@RequestParam com.walkhub.walkhub.domain.rank.domain.type.DateType dateType) {
넵

2022-02-14 05:14 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
> +			.findAllByDateTypeAndCreatedAtBetweenOrderByRankingDesc(dateType.toString(), localDate, LocalDate.now())
아 그러네요

2022-02-14 05:15 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
> +	public SchoolRankResponse execute(SchoolDateType schoolDateType) {
넵

2022-02-14 05:17 UTC, softpeanut approved these changes

2022-02-14 05:55 UTC, parksangwoo1617 approved these changes

2022-02-14 08:01 UTC, eogus2513 approved these changes

2022-02-14 14:44 UTC, jhhong0509 approved these changes

2022-02-14 14:46 UTC, merged