🔀 :: (#335) 칼로리 최대 레벨 설정 API
Walkhub/Walkhub-Server pull request #337
Opened 2022-02-13 20:49 UTC by softpeanut

close #335

2022-02-13 21:22 UTC, jhhong0509 requested changes

2022-02-13 21:22 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/calorielevel/presentation/CalorieLevelController.java
> +    @GetMapping("/levels/lists")
이거 endpoint가 이상합니다

2022-02-14 05:19 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/calorielevel/presentation/CalorieLevelController.java
> +    @GetMapping("/levels/lists")
칼로리 관련 api가 하나 더 생기면서 /users에서 분리해 /levels 라는 도메인을 하나 더 만들었습니다
API 명세서 보시면 수정되어 있습니다

2022-02-14 06:00 UTC, lyutvs approved these changes

2022-02-14 06:01 UTC, glay415 approved these changes

2022-02-14 06:03 UTC, eogus2513 approved these changes

2022-02-14 06:53 UTC, jhhong0509 approved these changes

2022-02-14 07:10 UTC, merged