🔀 :: (#358) 반 가입 방식 변경
Walkhub/Walkhub-Server pull request #359
Opened 2022-02-15 12:02 UTC by softpeanut

close #358

2022-02-15 12:03 UTC, eogus2513 approved these changes

2022-02-15 13:20 UTC, glay415 approved these changes

2022-02-15 13:50 UTC, eogus2513 approved these changes

2022-02-15 13:50 UTC, jhhong0509 requested changes

2022-02-15 13:50 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/service/JoinSectionService.java
> +        if (user.getSection() != null) {
`user.getSection()`을 하면 예외를 던지게 해놔서 이렇게 하면 안될 것 같은데
User 엔티티에 `hasSection()`같은 메소드 하나 맹글자

2022-02-15 14:09 UTC, parksangwoo1617 approved these changes

2022-02-15 17:35 UTC, lyutvs approved these changes

2022-02-16 00:21 UTC, glay415 approved these changes

2022-02-16 00:23 UTC, eogus2513 approved these changes

2022-02-16 00:43 UTC, jhhong0509 approved these changes

2022-02-16 00:49 UTC, merged