🔀 :: (#544) 반 코드 확인 체크 Api
Walkhub/Walkhub-Server pull request #545
Opened 2022-03-08 05:49 UTC by leeseojune53

2022-03-08 05:51 UTC, jhhong0509 requested changes

2022-03-08 05:51 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +
음?

2022-03-08 05:51 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/CheckClassCodeRequest.java
> +    @NotBlank(message = "code는 비어있으면 안됩니다.")
메세지 통일점

2022-03-08 05:54 UTC, jhhong0509 approved these changes

2022-03-08 07:28 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/service/CheckClassCodeService.java
> +@Service
이거 @Service 어노테이션 그대로 해요?

2022-03-08 13:57 UTC, leeseojune53 commented on src/main/java/com/walkhub/walkhub/domain/user/service/CheckClassCodeService.java
> +@Service
저게 아직 머지안되어서 ㅜㅜ

2022-03-09 03:35 UTC, softpeanut approved these changes

2022-03-09 07:39 UTC, lyutvs approved these changes

2022-03-09 07:43 UTC, merged