🔀 :: (#546) 내 정보 수정 Api 수정
Walkhub/Walkhub-Server pull request #547
Opened 2022-03-08 14:32 UTC by leeseojune53

2022-03-08 23:37 UTC, jhhong0509 requested changes

2022-03-08 23:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> -        updateSchoolInfoService.execute(request);
이건 왜 지우셨죠..?

2022-03-08 23:37 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
> +    private Long schoolId;
이거 학교만 / 프사만 바꿀 수 있어야 하는거 아닌가요?

2022-03-09 05:17 UTC, leeseojune53 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> -        updateSchoolInfoService.execute(request);
수정사항에 저거를 내 정보수정으로 넣는다고 되어있어요

2022-03-09 06:34 UTC, jhhong0509 approved these changes

2022-03-09 07:38 UTC, lyutvs approved these changes

2022-03-09 07:39 UTC, parksangwoo1617 reviewed
라우터 어디갔나유

2022-03-09 07:41 UTC, parksangwoo1617 approved these changes

2022-03-09 07:42 UTC, parksangwoo1617 commented
있었네유

2022-03-09 07:43 UTC, merged