🔀 :: (#624) 학교 랭킹 조회 및 검색 api
Walkhub/Walkhub-Server pull request #633
Opened 2022-04-02 15:44 UTC by glay415

초중고 필터링은 보류입니다

2022-04-02 15:51 UTC, parksangwoo1617 requested changes

2022-04-02 15:51 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
> +	}
querydsl에서 like는 해당 문자열이 완전히 같은 경우만 결과를 반환한다고 합니다 
검색에서는 contains가 더 적절할 거 같아요

2022-04-02 15:51 UTC, parksangwoo1617 commented
코드스멜도 해결해주세용

2022-04-02 15:52 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
> +	}
덧붙여서 querydsl의 like를 사용해서 실제 sql에서의 like를 사용하려면 직접 %를 붙여줘야한다고 하네요

2022-04-03 00:36 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
> +                                           @RequestParam SchoolDateType schoolDateType) {
한 번에 묶어서 받는게 더 깔끔할 것 같아요

2022-04-03 00:36 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolListResponse.java
> +        @QueryProjection
dto와 vo를 분리하는게 좋을 것 같습니다

2022-04-03 03:21 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
> +public class SchoolRankRepositoryCustomImpl implements SchoolRankRepositoryCustom{
`{` 앞에 띄어쓰기

2022-04-03 03:21 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
> +	public List<SchoolResponse> getSchoolListAndSearch(String name, Sort sort, Scope scope,
Response 주는거랑 Repository의 DTO랑 구분좀..

2022-04-03 08:03 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
> +	}
아 글쿤요 수정했습니다

2022-04-03 12:59 UTC, parksangwoo1617 approved these changes

2022-04-04 10:02 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
> +                                           @RequestParam SchoolDateType schoolDateType) {
넵

2022-04-04 11:03 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/request/SchoolSearchRequest.java
> +public class SchoolSearchRequest {
not null인 건 validation 해줘야 할 것 같아요

2022-04-04 11:47 UTC, jhhong0509 approved these changes

2022-04-04 12:28 UTC, softpeanut approved these changes

2022-04-04 13:08 UTC, merged