🔀 :: (#61) 건강 정보 입력 API
Walkhub/Walkhub-Server pull request #78
Opened 2022-01-11 01:56 UTC by parksangwoo1617

close #61

2022-01-11 02:19 UTC, eogus2513 approved these changes

2022-01-11 02:44 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
> +    @NotNull(message = "height는 null일 수 없습니다.")
@NotBlank말고 @NotNull을 하신 이유가 있을까요?

2022-01-11 03:39 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
> +    @NotNull(message = "height는 null일 수 없습니다.")
`@NotBlank`는 String타입 전용이라서 못 쓰는걸로 알아요

2022-01-11 03:39 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
`@PutMapping`을 사용해야 할 것 같습니다

2022-01-11 11:19 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
수정하겠습니다

2022-01-11 14:29 UTC, jhhong0509 approved these changes

2022-01-11 14:58 UTC, jeongjiwoo0522 commented
Merge Comflict 해결해주시고 
tasks 모두 완료해주세요

2022-01-11 23:50 UTC, glay415 approved these changes

2022-01-11 23:53 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
> +        userRepository.save(user);
21번줄 이 부분은 필요 없을것 같습니다

2022-01-12 03:26 UTC, jeongjiwoo0522 requested changes
.

2022-01-12 04:20 UTC, parksangwoo1617 commented on src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
> +        userRepository.save(user);
그렇네요 수정하겠습니다

2022-01-12 06:40 UTC, jeongjiwoo0522 approved these changes

2022-01-12 06:53 UTC, merged