🔀 :: (#70) fcm setting
Walkhub/Walkhub-Server pull request #83
Opened 2022-01-11 13:39 UTC by lyutvs

close #70

2022-01-11 14:02 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/SendDto.java
> +@AllArgsConstructor
@AllArgsConstructor는 필요 없을 것 같습니다

2022-01-11 14:02 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
> +        if(sendDto.getUser().haveDeviceToken()) {
디바이스 토큰이 없을 때는 예외 발생이 안되는 건가요?

2022-01-11 14:03 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/SendDto.java
> +@AllArgsConstructor
수정하겠습니다

2022-01-11 14:04 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
> +        if(sendDto.getUser().haveDeviceToken()) {
디바이스 토큰이 없다면 예외 발생을 하고 if문 밖에서 로직을 수행하는 건 어떤가요?

2022-01-11 14:05 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
> +        if(sendDto.getUser().haveDeviceToken()) {
디바이스 토큰이 없는 경우가...있을까요...?
따로 로직 빼서 처리 하는거 고민 해보겠습니당

2022-01-11 14:10 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +public class NotificationEntity {
Notification이거를 NotificationEntity로 바꾸신 이유가 있을까요?

2022-01-11 14:10 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
> +    public NotificationList(NotificationEntity notificationId, User userId) {
notificationId -> notification으로 변수명을 바꿔야될것 같아요

2022-01-11 14:12 UTC, jhhong0509 requested changes

2022-01-11 14:12 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +public class NotificationEntity {
따로 이유가 있어도 테이블 이름이 notification_entity가 될 것 같은데 `@Table(name = "")` 이런식으로 설정 부탁드립니다

2022-01-11 14:12 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
> +	}
boolean 타입 값을 반환하는 메서드는 되도록 is~ 로 시작하는게 좋아요 

isHaveDeviceToken()으로 하면 더 쌈박할것 같습니다

2022-01-11 14:13 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +public class NotificationEntity {
firebase 에서 Notification 이라는 클래스를 사용 해야 하는데 이름이 겹쳐서 바꿨습니다

2022-01-11 14:14 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
> +	}
이 메소드는 언제 어디에서 사용되나요?

2022-01-11 14:14 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +public class NotificationEntity {
같은 패키지만 아니면 클래스명 겹치는건 괜찮아요

2022-01-11 14:24 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
> +	}
CoolNotification 에서 유저가 디바이스 토큰 가지고 있냐 판벼 할려고 만드렀습니다

2022-01-11 14:25 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
> +                    .setNotification(
제가 알기론 click_action이나 value값 같은건 나중에 추가하실건가요?

2022-01-11 14:25 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
> +public interface FcmUtil {
Util 클래스는 해당 클래스에 속하는 친구들에 대한 static method를 정의하는걸로 알아서 facade가 더 맞는 것 같아요

2022-01-11 14:55 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
> +public class NotificationEntity {
아 넵 알겠습니다

2022-01-11 15:01 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
> +public interface FcmUtil {
그러기엔 이미 싸질러 놓은게 많은데요 쩝

2022-01-11 15:07 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
> +public interface FcmUtil {
그러면 SmsUtil 도 바꿔야 하나요??

2022-01-11 15:50 UTC, jeongjiwoo0522 commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
> +public interface FcmUtil {
그러게요

2022-01-12 02:10 UTC, softpeanut commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
> +        List<String> deviceTokens = sendDto.getUsers().stream().map(User::getDeviceToken).collect(Collectors.toList());
이거 줄바꿈 한 번만..ㅎㅎ

2022-01-12 02:12 UTC, lyutvs commented on src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
> +        List<String> deviceTokens = sendDto.getUsers().stream().map(User::getDeviceToken).collect(Collectors.toList());
😥

2022-01-12 06:38 UTC, jhhong0509 approved these changes

2022-01-12 06:43 UTC, eogus2513 approved these changes

2022-01-12 06:56 UTC, softpeanut approved these changes

2022-01-12 07:27 UTC, glay415 approved these changes

2022-01-12 08:09 UTC, merged