🔀 :: (#73) Image Utility
Walkhub/Walkhub-Server pull request #84
Opened 2022-01-11 15:49 UTC by eogus2513

close #73

2022-01-11 16:43 UTC, jhhong0509 requested changes

2022-01-11 16:43 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/ImageUtil.java
> +public interface ImageUtil {
클래스명 iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

2022-01-11 16:43 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Properties.java
> +public class S3Properties {
@ConfigurationProperties로 변경해 주세요

2022-01-11 16:43 UTC, jhhong0509 commented on src/test/java/com/walkhub/walkhub/IntegrationTest.java
> +public class IntegrationTest {
무엇을 위한 테스트 인가요....?

2022-01-11 16:43 UTC, jhhong0509 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3.java
> +public class S3 implements ImageUtil {
S3 파일 업로드 로직은 Util이라기엔 애매해서 Util 말고 Facade로 바꾸는게 나을 것 같습니다.
> 아마 Util 클래스는 원래 static method들로 구성된 클래스인걸로 알아요.

추가로 클래스명이 S3는 너무 단순해서 목적을 파악하기 힘든 것 같습니다. S3Util, S3Facade와 같이 바꿔주세요

2022-01-11 23:26 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3.java
> +public class S3 implements ImageUtil {
수정하겠습니다.

2022-01-11 23:26 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Properties.java
> +public class S3Properties {
넵 수정하겠습니다.

2022-01-11 23:58 UTC, jeongjiwoo0522 approved these changes

2022-01-12 01:48 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/ImageUtil.java
> +public interface ImageUtil {
그래로 진행하겠습니다 ㅎㅎ

2022-01-12 01:50 UTC, jhhong0509 approved these changes

2022-01-12 02:04 UTC, glay415 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Properties.java
> +}
굳이 @value를 사용하지 않고 @ConfigurationProperties를 사용하신 이유가 무엇인가요

2022-01-12 02:07 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Facade.java
> +            throw ImageNotFoundException.EXCEPTION;
뭐라해야 할지 몰라서 그렇게 넣었습니다

2022-01-12 02:08 UTC, eogus2513 commented on src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Properties.java
> +}
@Value 어노테이션은 환경 변수가 어디에서 사용되었는지 추적이 어려워서 @ConfigurationProperties를 더 권장합니다

2022-01-12 03:28 UTC, lyutvs approved these changes

2022-01-12 06:47 UTC, jeongjiwoo0522 approved these changes

2022-01-12 06:55 UTC, softpeanut approved these changes

2022-01-12 07:16 UTC, merged